dist: jammy

language: python

cache:
  directories:
    - $HOME/.cache/pre-commit

python:
  - "3.10"
  - "3.11"

install:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.cargo/env
  - uv pip install -q pip wheel pre-commit pytest-cov nbqa pylint
  - uv pip install -q .[examples]
  # - uv pip install -q -r notebooks/notebook_requirements.txt
  # - uv pip list
  - pre-commit install
  - uv pip freeze
  - uv pip check || true # verify all packages are compatible but do not fail if not

script:
  # style checking
  - pre-commit run --all-files --show-diff-on-failure

  # test import
  - pushd /tmp; python -c "import mammal"; popd;

  # run notebooks qa
  # - nbqa pylint notebooks/*.ipynb --disable=all --enable=E

  # run unit tests
  - python -m pytest --durations=40 --cov=mammal --cov-fail-under=45 --capture=no mammal/examples/tests

git:
  depth: 1

notifications:
  email: false
